#SQLAlchemyLoggerReporter
SQLAlchemyLoggerReporter:
 SQLAlchemyReporter: *reference #see mellon_plugin.reporter.configure.yaml
 table_name: table_name #optional table_name #name of table to report secrets into