#SQLAlchemyEngine
SQLAlchemyEngine:
 dsn: valid:/sqlalchemy/dsn/string # i.e. sqlite:///somefile.db
 kwargs: #optional keyword arguments for sqlalchemy.create_engine()
  arg1: value1
  arg2: value2

#SQLAlchemyReporter
SQLAlchemyReporter:
 SQLAlchemyEngine: *reference #see mellon_plugin.reporter.configure.yaml
 utc_time: False #optionally record datetime as UTC, defaults to local tz