#Flask configuration
Flask:
 settings: # Key value pairs passed into the Flask application server
  key_1: value_1
 kwargs: # kwargs passed into Flask app initialization
  param_1: value_1

ResourcePagination:
 max_limit: 50 #upper bound on api request limit parameter 
 default_limit: 20 #default api request limit, used if not available in request

#Flask Restless configuration
FlaskRestless
 settings: #optional settings segment
  default: #optional default segment
   setting_1: value_1 # some default config setting applied to all appi endpoints
  resource_1: #api resource specific settings.  Should match SQLAlchemy model name for resource
   setting_1: value_1 # this setting would only apply to the endpoint_1 resource